version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    # check weekly on Sunday at 1am UTC
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "01:00"
    labels:
      - "github-action dependencies"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    # check weekly at 2am UTC
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    labels:
      - "pip dependencies"
