codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
github_checks:
    annotations: false
coverage:
  precision: 3
  round: nearest
  range: "10...100"
  status:
    patch: off
    project:
      default: yes
      target: auto
      threshold: null
      base: pr
      flags: null
      if_ci_failed: error
