# .readthedocs.yml

version: 2

sphinx:
    builder: html
    configuration: docs/conf.py
    #fail_on_warning: true

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  apt_packages:
    - iputils-ping
    - build-essential
    - curl
    - gfortran
    - csh
    - zsh
    - tcsh

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

