#!/bin/sh
BUILDTEST_ROOT=/hpc/hpcswadm/BuildTest/
BUILDTEST_SOURCEDIR=${BUILDTEST_ROOT}"source"
BUILDTEST_EASYCONFIGDIR=${BUILDTEST_ROOT}"easybuild"
BUILDTEST_MODULEROOT=/nfs/grid/software/RHEL7/easybuild/modules
BUILDTEST_TESTDIR=$BUILDTEST_ROOT"testing"

export BUILDTEST_ROOT
export BUILDTEST_SOURCEDIR
export BUILDTEST_EASYCONFIGDIR
export BUILDTEST_MODULEROOT
export BUILDTEST_TESTDIR
