name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - shahzebsiddiqui
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Bug Description
      description: |
        Please describe the bug you are facing with an output of buildtest command and expected error. Please include content of buildspec file if issue is related.
      placeholder: |
        ```console
          $ buildtest <command>
        ```

        Include content of buildspec if necessary
        ```yaml
            buildspecs:
              hello_world:
                type: script
                executor: generic.local.sh
                run: echo "hello world"
        ```
    validations:
      required: true

  - type: textarea
    id: reproduce-error
    attributes:
      label: Steps to reproduce the error
      description: |
        Please provide a list of steps to reproduce the error in-order for us to troubleshoot your issue.
    validations:
      required: true

  - type: textarea
    id: version-commit
    attributes:
      label: Version and HEAD commit
      description: |
        Please copy and paste output of the commands `buildtest --version` and `git log -1` in order for us to know the
        version of the buildtest you are using and the HEAD commit. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. Please provide the output of the commands `buildtest info` and `buildtest debugreport`.
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: slackterms
    attributes:
      label: Post question in Slack
      options:
        - label: I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue
          required: true

  - type: checkboxes
    id: issueterms
    attributes:
      label: Is there an existing issue
      options:
        - label: I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue
          required: true

  - type: markdown
    attributes:
      value: |
        We encourage you provide a detailed explanation of the issue including link to output, logfile, error message and screenshots in order for us troubleshoot the issue.
        If you have a quick question please post your question in `#general` channel on [buildtest slack](https://hpcbuildtest.slack.com/) first.

        Thanks for taking the time to contribute back to buildtest.
