# This pipeline is run at NERSC at gitlab instance: https://software.nersc.gov

variables:
  SCHEDULER_PARAMETERS: "-N 1 -M escori -q compile -t 30"

stages:
  - regression
  - validate

cori_pr_regression_test:
  tags: ["cori"]
  stage: regression
  rules:
    - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event" || $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"'
      when: manual

  script:
    - whoami
    - module load python/3.8-anaconda-2020.11
    - git branch
    - conda create -p $CI_PROJECT_DIR/.conda python=3.8
    - source activate $CI_PROJECT_DIR/.conda
    - source setup.sh
    - pip install -r docs/requirements.txt
    - rm -rf ~/.buildtest/
    - coverage run -m pytest -vra tests
    - coverage report -m
    # CODECOV_TOKEN environment must be set, this value is stored in CI/CD variable SECRET_CODECOV_TOKEN at https://software.nersc.gov/siddiq90/buildtest/-/settings/ci_cd
    - export CODECOV_TOKEN=$SECRET_CODECOV_TOKEN
    - bash <(curl -s https://codecov.io/bash)
    - source deactivate
    - conda env remove -p $CI_PROJECT_DIR/.conda -y


validate_cori_testsuite:
  tags: ["cori"]
  stage: validate
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"'
      when: manual
  script:
    - module load python
    - conda create -n buildtest python=3.8
    - source activate buildtest
    - source setup.sh
    - git clone https://github.com/buildtesters/buildtest-cori
    - cd buildtest-cori
    - mkdir -p $HOME/.buildtest
    - cp .buildtest/config.yml $HOME/.buildtest/config.yml
    - buildtest config validate
    - buildtest buildspec find --root buildspecs
    - source deactivate 
    - conda env remove -n buildtest -y