# This pipeline is run at ALCF at gitlab instance: https://gitlab.jlse.anl.gov

stages:
  - sync
  - regression

sync_buildtest_jlse_mirror:
  tags: [shell, jlse]
  stage: sync
  only:
    refs:
    - schedules
  script:
    - cd $CI_PROJECT_DIR
    - mkdir tmp && cd tmp
    - git clone https://github.com/buildtesters/buildtest
    - cd buildtest
    - git remote add jlse_mirror git@gitlab-server-jlse-01.jlse.anl.gov:e4s/shahzebsiddiqui/buildtest.git
    - git remote -v
    - git branch
    - git push jlse_mirror devel


jlse_pr_regression_test:
  tags: [shell, jlse]
  stage: regression
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"'
      when: always
  script:
    - whoami
    - git branch
    - ml conda
    - python -m venv $CI_PROJECT_DIR/.pyenv
    - source $CI_PROJECT_DIR/.pyenv/bin/activate
    - source setup.sh
    - pip install -r docs/requirements.txt
    - python $BUILDTEST_ROOT/buildtest/tools/unittests.py -c
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    # CODECOV_TOKEN environment must be set, this value is stored in CI/CD variable at https://gitlab.jlse.anl.gov/e4s/shahzebsiddiqui/buildtest/-/settings/ci_cd
    - ./codecov --verbose -t $CODECOV_TOKEN
    - echo $?
    - source deactivate
    - rm -rf $CI_PROJECT_DIR/.pyenv -y
