# This pipeline is run at ALCF at gitlab instance: https://gitlab.jlse.anl.gov

stages:
  - sync
  - regression

sync_buildtest_jlse_mirror:
  tags: [shell, jlse]
  stage: sync
  only:
    refs:
    - schedules
  script:
    - cd $CI_PROJECT_DIR
    - mkdir tmp && cd tmp
    - git clone https://github.com/buildtesters/buildtest
    - cd buildtest
    - git remote add jlse_mirror git@gitlab-server-jlse-01.jlse.anl.gov:e4s/shahzebsiddiqui/buildtest.git
    - git remote -v
    - git branch
    - git push jlse_mirror devel


jlse_pr_regression_test:
  tags: [shell, jlse]
  stage: regression
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"'
      when: always
  script:
    - whoami
    - git branch
    - conda create -p $CI_PROJECT_DIR/.conda python=3.8 -y
    - source activate $CI_PROJECT_DIR/.conda
    - source setup.sh
    - pip install -r docs/requirements.txt
    - python $BUILDTEST_ROOT/buildtest/tools/unittests.py
    # CODECOV_TOKEN environment must be set, this value is stored in CI/CD variable SECRET_CODECOV_TOKEN at https://gitlab.jlse.anl.gov/e4s/shahzebsiddiqui/buildtest/-/settings/ci_cd
    - export CODECOV_TOKEN=$SECRET_CODECOV_TOKEN
    - bash <(curl -s https://codecov.io/bash)
    - source deactivate
    - conda env remove -p $CI_PROJECT_DIR/.conda -y
