buildspecs:
  additionalProperties_compiler_config:
    executor: local.bash
    type: compiler
    description: "Test additionalProperies in compiler config section, FOO: BAR"
    source: src/hello.f90
    compilers:
      name: ["PrgEnv-cray"]
      config:
        PrgEnv-cray@2.6.2:
          FOO: BAR
          fflags: "-O1"
          module:
            swap: [PrgEnv-intel, PrgEnv-cray/2.6.2]
