name: jlse regtest

on:
  pull_request:
    branches: [devel]
    paths:
      - 'buildtest/**'
      - 'tests/**'
      - '.github/workflows/jlse.yml'
      - 'requirements.txt'
      - 'pyproject.toml'

jobs:

  regtest_on_jlse:
    runs-on: jlse
    steps:
      - uses: actions/checkout@v4
      - name: "Regression Test on JLSE"
        shell: bash
        run: |
          hostname
          pwd
          module load conda
          python -m venv $CI_PROJECT_DIR/.pyenv
          source $CI_PROJECT_DIR/.pyenv/bin/activate
          source setup.sh
          pip install -r docs/requirements.txt
          python $BUILDTEST_ROOT/buildtest/tools/unittests.py -c