name: Regression Test in Container

on:
  pull_request:
    branches: [ devel ]
    
jobs:
  buildtest_tutorial_container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/buildtesters/buildtest_spack
      options: "-it --user spack"
    steps:
      - name: regression test in container
        shell: bash
        run: | 
          # env
          # whoami
          # id     
          # ls -ld $HOME
          # echo $HOME
          # cd $GITHUB_WORKSPACE
          # ls -la $GITHUB_WORKSPACE
          set +xe
          . /etc/profile
          # module --version
          # module avail
          # spack --version
          module load python
          which python3
          # python3 --version3
          # cd $GITHUB_WORKSPACE
          # ls -la
          git clone https://github.com/buildtesters/buildtest.git
          cd buildtest
          source setup.sh
          export HOMEDIR=`pwd`
          export BUILDTEST_CONFIGFILE=$HOMEDIR/buildtest/settings/spack_container.yml
          python $HOMEDIR/buildtest/tools/unittests.py -c
          returncode=$?
          if [ $returncode != 0 ]; then exit $returncode; fi

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30