name: Regression Test in Container

on:
  pull_request:
    branches: [devel]
    paths:
      - 'buildtest/**'
      - 'tests/**'
      - '.github/workflows/regressiontest_container.yml'
      - 'requirements.txt'
      - 'pyproject.toml'
    
jobs:
  buildtest_tutorial_container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/buildtesters/buildtest_spack:spack-sc23
      options: "-it --user root"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: regression test in container
        shell: bash
        run: | 
          set +xe
          . /etc/profile
          which csh zsh
          module load python
          python3 -m venv env
          source env/bin/activate
          source setup.sh
          python $BUILDTEST_ROOT/buildtest/tools/unittests.py -c --pytest="-m spack"
          returncode=$?
          if [ $returncode != 0 ]; then exit $returncode; fi
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
