name: Regression Test in Container

on:
  pull_request:
    branches: [ devel ]
    
jobs:
  buildtest_tutorial_container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/buildtesters/buildtest_spack
      options: "-it --user root"
    steps:
      - uses: actions/checkout@v3
      - name: regression test in container
        run: | 
          env
          whoami
          id     
          ls -la $HOME
          echo $HOME
          cd $GITHUB_WORKSPACE
          ls -la $GITHUB_WORKSPACE
          set +e
          . /etc/profile
          module --version
          module avail
          spack --version
          . scripts/spack_container/setup.sh
          python $BUILDTEST_ROOT/buildtest/tools/unittests.py -c
          returncode=$?
          if [ $returncode != 0 ]; then exit $returncode; fi
